### ISSUE TITLE
Auction house.

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedPointsSystem#6]
Currently don't have that large of a solid concept for this, and it _could very well_ go inline with the shop (although this might take some effort and delays to just implement right now)

But I noticed one of your studio's other extensions for phpbb, https://github.com/phpBB-Studio/DateTopicStarterTemplate, and it gave me an idea, which you might be able to grasp from the title.
whether they are 
**closed** (only accessible by those who enter as participants before the auction opens or not) or
**open** (anyone can bid) 
and 
if there is **auto bid** (users can set a max bid price and it will auto out bid to that price)
and a **buy price** (users can outright buy an item)
would probably be a down the line kind of thing, if done at all by you guys.

there is also the prospect that I'm totally missing the intention's you have with the shop part of this extension, and that this would be totally useless, _or it might already be a part of the shop, and just have no idea._

**Comment by 3D-I** [comment]
No, this extension is used to collect points with a hundred actions native to the phpBB system.

It is ready to be expanded in any way, for example other actions by other extensions, a Shop, a Bank, a Lottery etc. ...

**Comment by mrgoldy** [comment]
This will indeed not be implemented within the APS itself.
The APS is just for collecting points and displaying 'some stuff' on the Display page.
Anything else will not be added to this extension, as that will be/become a disaster to maintain.

Moreover, a Shop is being worked on (which is a different extension), but it's not yet done. So it's kinda futile requesting features for that..

**Comment by 3D-I** [comment]
The shop is out, therefore locking.
