### ISSUE TITLE
Advanced Shop System Logging

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedPointsSystem#7]
I figure this is at least something you guys are figuring to get out down the road, but it would seem that purchases (and subsequent uses of items from 'ASS') do not contribute to the APS logs, 

which, if forum owners and administrators were unaware of, could lead to some negative things.

**Comment by 3D-I** [comment]
All actions in regards to APS (receiving points for an APS action) are logged in APS.

All stuff in regards to the shop are logged in ASS.

It is not an APS action when using a 'points' item.
